import "./globals.css";
import { Roboto } from "next/font/google";
import { Header } from "@/app/components";
import clsx from "clsx";

const roboto = Roboto({ weight: ["400", "500", "700", "900"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, "bg-white")}>
        <Header />

        {children}
      </body>
    </html>
  );
}
